services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
      - audio-data:/app/data/audio
      - db-data-dev:/app/data
      - whisper-cache:/root/.cache/whisper
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./data/transcriptions_dev.db
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - redis
      - ollama
    networks:
      - transcribe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8080  # Docker backend external port
    depends_on:
      - backend
    networks:
      - transcribe-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Use 6380 externally to avoid conflict with local Redis
    volumes:
      - redis-data:/data
    networks:
      - transcribe-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  # Expose for local dev access
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - transcribe-network

volumes:
  audio-data:
  db-data-dev:
  redis-data:
  ollama-data:
  whisper-cache:
  frontend-node-modules:

networks:
  transcribe-network:
    driver: bridge
