services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8081:8000"
    volumes:
      - audio-data-prod:/app/data/audio
      - db-data-prod:/app/data
      - whisper-cache:/root/.cache/whisper
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:///./data/transcriptions_prod.db
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - redis
      - ollama
    networks:
      - transcribe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - transcribe-network
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - transcribe-network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - transcribe-network

volumes:
  audio-data-prod:
  db-data-prod:
  redis-data:
  ollama-data:
  whisper-cache:

networks:
  transcribe-network:
    driver: bridge
